name = "versete-biblice"
main = "src/index.ts"
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[vars]
CACHE_VERSION = "v1"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
