name = "versete-biblice"
main = "src/index.ts"
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[placement]
mode = "smart"

# Cron trigger for scheduling daily Bible verses
# Runs at midnight on the 1st day of every month
[triggers]
crons = ["0 0 1 * *"]
